In [10]:
'''
Jorge Carranza Pena
Assignment 3
EECE 2146
20563986
'''
import numpy as np


In [11]:
# Question 1
A = np.identity(n=2)
det = np.linalg.det(A)

print(f"Det(A) = {det}")

if det != 0:
    print("I2 is reversible, determinant is not zero")
else:
    print("I2 is not reversible, determinant is zero")

Det(A) = 1.0
I2 is reversible, determinant is not zero


In [12]:
# Question 2
A = np.identity(n=2)

inverse = np.linalg.inv(A)

print("Identity Matrix: \n", A)
print("Inverse of Identity Matrix:\n", inverse)

Identity Matrix: 
 [[1. 0.]
 [0. 1.]]
Inverse of Identity Matrix:
 [[1. 0.]
 [0. 1.]]


In [13]:
# Question 3
A = np.array([
    [10, 8],
    [4, 4]
])
print(f"det(A) = {np.linalg.det(A)}")
inverse = np.linalg.inv(A)

print("Identity Matrix: \n", A)
print("Inverse of Identity Matrix:\n", inverse)

det(A) = 7.999999999999998
Identity Matrix: 
 [[10  8]
 [ 4  4]]
Inverse of Identity Matrix:
 [[ 0.5  -1.  ]
 [-0.5   1.25]]


In [15]:
# Question 4
A = np.array([
    [2, 4],
    [4, 8]
])
print(f"det(A) = {np.linalg.det(A)}")
try:
    inverse = np.linalg.inv(A)
except Exception as err:
    inverse = f"An error occured: {err}"

print("Identity Matrix: \n", A)
print("Inverse of Identity Matrix:\n", inverse)


det(A) = 0.0
Identity Matrix: 
 [[2 4]
 [4 8]]
Inverse of Identity Matrix:
 An error occured: Singular matrix


In [ ]:
# Question 5 - CRAMER'S RULE
D = np.array([
    [2, 4],
    [6, 3]
])

D_x = np.array([
    [-10, 4],
    [6, 3]
])

D_y = np.array([
    [2, -10],
    [6, 6]
])

det_D = np.linalg.det(D)
det_D_x = np.linalg.det(D_x)
det_D_y = np.linalg.det(D_y)

print(f"det(D) = {det_D}")
print(f"det(D_x) = {det_D_x}")
print(f"det(D_y) = {det_D_y}")

x = det_D_x / det_D
y = det_D_y / det_D

print(f"x = {x}, y = {y}")

det(D) = -17.999999999999996
det(D_x) = -54.00000000000001
det(D_y) = 72.0
x = 3.000000000000001, y = -4.000000000000001
