In [10]:
'''
Jorge Carranza Pena
Assignment 3
EECE 2146
20563986
'''
import numpy as np

In [11]:
# Question 1

x = np.array([
    [2, 4],
    [5, 4]
])
y = np.array([
    [1, 2],
    [8, 6]
])
print(x + y)

[[ 3  6]
 [13 10]]


In [12]:
# Question 2

x = np.array([
    [2, 4],
    [5, 4]
])
print(3 * x)

[[ 6 12]
 [15 12]]


In [13]:
# Question 3

x = np.array([
    [8, 2],
    [6, 2]
])
y = np.array([
    [4],
    [2]
])
if x.shape != y.shape:
    raise ValueError("Matrices must have the same shape for addition.")

result = x + y
print(result)

ValueError: Matrices must have the same shape for addition.

In [ ]:
# Question 4

x = np.array([
    [4, 1],
    [4, 2]
])
y = np.array([
    [2, 4],
    [9, 4]
])
print(np.dot(x, y))

[[17 20]
 [26 24]]


In [ ]:
# Question 5

y = np.array([
    [3, 4],
    [4, 5]
])

x = np.identity(2, int)

print(np.dot(x, y))

[[3 4]
 [4 5]]


In [ ]:
# Question 6

x = np.array([
    [6, 2],
    [1, 3]
])
y = np.array([
    [4],
    [1]
])
print(np.dot(x, y))

[[26]
 [ 7]]
