In [23]:
'''
Jorge Carranza Pena
MIDTERM
EECE 2146
20563986
'''
import numpy as np

In [24]:
# Q1

print((1j)**6)

(-1+0j)


In [25]:
# Q2

print(12j + (4 + 5j))

(4+17j)


In [26]:
# Q3

print((5-4j)*(5+4j))

(41+0j)


In [27]:
# Q4

print((2j)/(8+1j))
print(2/65, 16/65)

(0.03076923076923077+0.24615384615384617j)
0.03076923076923077 0.24615384615384617


In [28]:
def cart_to_pol(x, y):
    r = np.sqrt(x**2 + y**2)
    theta_rad = np.arctan2(y, x)
    theta_deg = np.rad2deg(theta_rad) # Converts to degrees
    if theta_deg < 0:
        theta_deg = 360 + theta_deg
    return(r, theta_rad, theta_deg)

def pol_to_cart(r, theta):
    x = r * np.cos(theta)
    y = r * np.sin(theta)
    return (x, y)

In [29]:
# Q5

r, t_rad, t_deg = cart_to_pol(-2, 25)
print(f"r = {r}, theta_rad = {t_rad}, theta_deg = {t_deg}")

r = 25.079872407968907, theta_rad = 1.6506263125071339, theta_deg = 94.57392125990086


In [30]:
# Q6

x, y = pol_to_cart(16, 3.2*np.pi)
print(f"x = {x}, y = {y}")

x = -12.944271909999163, y = -9.404564036679565


In [31]:
# Q9

a = np.array([
    [5, 6],
    [2, 1]
])

b = np.array([
    [8],
    [1]
])

print(np.dot(a, b))

[[46]
 [17]]


In [32]:
'''
Q10
Solve the system of linear equations via the matrix inversion method:
6x + 5y = 2
2x - 2y = 4
'''

A = np.array([
                    [6, 5],
                    [2, -2]
                ])

B = np.array([
                [2],
                [4]
            ])

'''
    Let X = [x]
            [y]
    AX = B
    X = (A^-1)B
'''

X = np.dot(np.linalg.inv(A) , B)

x = X[0][0]
y = X[1][0]

print(f"x = {x}, y = {y}")

print(f"{round(6*(x) + 5*(y))} = 2")
print(f"{round(2*(x) - 2*(y))} = 4")

print("CHECK\n", np.linalg.solve(A, B))

x = 1.090909090909091, y = -0.9090909090909092
2 = 2
4 = 4
CHECK
 [[ 1.09090909]
 [-0.90909091]]


In [33]:
'''
Q11
Solve the system of linear equations via the matrix inversion method:
2x + 5z = 2
4x - y = 4
2x + 5y - 2z = 8
'''

A = np.array([
                    [2, 0, 5],
                    [4, -1, 0],
                    [2, 5, -2]
                ])

B = np.array([
                [2],
                [4],
                [8]
            ])

'''
    Let X = [x]
            [y]
    AX = B
    X = (A^-1)B
'''

X = np.dot(np.linalg.inv(A) , B)

x = X[0][0]
y = X[1][0]
z = X[2][0]

print(f"x = {x}, y = {y}, and z = {z}")

print(f"{round(2*x + 5*z)} = 2")
print(f"{round(4*x - y)} = 4")
print(f"{round(2*x + 5*y - 2*z)} = 8")


print("CHECK\n", np.linalg.solve(A, B))

x = 1.263157894736842, y = 1.0526315789473686, and z = -0.10526315789473686
2 = 2
4 = 4
8 = 8
CHECK
 [[ 1.26315789]
 [ 1.05263158]
 [-0.10526316]]
